apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine-container
      image: alpine:latest
      command: ["sleep", "infinity"]
      envFrom:
        - configMapRef:
            name: {{ .Values.wsl_config | quote }}
      volumeMounts:
        - name: secrets
          mountPath: /app/.env
          subPath: .env
          readOnly: true
      env:
      - name: WINDOWS_HOST
        valueFrom:
          configMapKeyRef:
            name: wsl-config
            key: WINDOWS_HOST
      - name: ADB_SERVER_SOCKET
        value: "tcp:$(WINDOWS_HOST):5037"
  volumes:
    - name: secrets
      secret:
        secretName: insta-automate-secret
