apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine-container
      image: alpine:latest
      command: ["sleep", "infinity"]
      envFrom:
        - configMapRef:
            name: {{ .Values.wsl_config | quote }}
