apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  storageClassName: {{ .Values.volume.storageClass }}