apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-auth-secret
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.pg.username | b64enc }}
  password: {{ .Values.pg.password | b64enc }}
