apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port.target }}
      targetPort: {{ .Values.port.target }}
      nodePort: {{ .Values.port.node }}
  type: NodePort
