apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}-worker
  template:
    metadata:
      labels:
        app: {{ .Values.app }}-worker
    spec:
      volumes:
        - name: insta-automate-secret
          secret:
            secretName: insta-automate-secret
      initContainers:
        - name: wait-for-prefect-server
          image: busybox:latest
          env:
            - name: PREFECT_HOST
              value: {{ .Values.app }}-server
            - name: PREFECT_PORT
              value: {{ .Values.server.port | quote }}
          command: ["sh", "-c", "until nc -z ${PREFECT_HOST} ${PREFECT_PORT}; do sleep 2; done "]
        - name: create-work-pool
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: PREFECT_API_URL
              value: "http://{{ .Values.app }}-server:{{ .Values.server.port }}/api"
          command:
            - sh
            - -c
            - |
              prefect work-pool create {{ .Values.server.workpool }} --type process || true
      containers:
        - name: {{ .Values.app }}-worker
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: PREFECT_API_URL
              value: "http://{{ .Values.app }}-server:{{ .Values.server.port }}/api"
            - name: PREFECT_TASKS_DEFAULT_NO_CACHE
              value: "true"
          command: ["prefect", "worker", "start", "--pool", "{{ .Values.server.workpool }}"]
        - name: telegram-event-listener
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: PREFECT_API_URL
              value: "http://{{ .Values.app }}-server:{{ .Values.server.port }}/api"
          command: ["ia", "telegram", "serve"]
          volumeMounts:
            - name: insta-automate-secret
              mountPath: /opt/prefect/.env
              subPath: .env
              readOnly: true
              
