apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-worker
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      initContainers:
        - name: wait-for-{{ .Values.app }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["prefect-k3s", "wait"]
        - name: create-work-pool
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: 
            - sh
            - -c
            - |
              prefect work-pool create {{ .Values.workpool }} --type process || true
      containers:
        - name: {{ .Values.app }}-worker
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["prefect", "worker", "start", "--pool", "{{ .Values.workpool }}"]
