apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | quote }}
  POSTGRES_DB: {{ .Values.db }}
  POSTGRES_PORT: {{ .Values.port | quote }}
