apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      volumes:
        - name: {{ .Values.app }}-data
          hostPath:
            path: {{ .Values.mount.host }}
            type: DirectoryOrCreate
      initContainers:
        - name: wait-for-prefect
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["prefect-k3s", "wait"]
        - name: {{ .Values.app }}-telegram-init
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["ia", "tl", "init"]
        - name: {{ .Values.app }}-db-init
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["ia", "db", "init"]
        - name: {{ .Values.app }}-flow-init
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["ia", "prefect", "deploy"]
      containers:
        - name: {{ .Values.app }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["ia", "prefect", "serve"]
          volumeMounts:
            - name: {{ .Values.app }}-data
              mountPath: {{ .Values.mount.target }}
          # - sh
          # - -c
          # - |
          #   sleep infinity
          