apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-worker
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      volumes:
        - name: {{ .Values.app }}-data
          hostPath:
            path: {{ .Values.mount.host }}
            type: DirectoryOrCreate
      initContainers:
        - name: wait-for-{{ .Values.app }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["prefect-k3s", "wait"]
        - name: create-work-pool
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: 
            - sh
            - -c
            - |
              prefect work-pool delete $IA_PREFECT_WORKPOOL
              prefect work-pool create $IA_PREFECT_WORKPOOL --type process
              prefect work-pool set-concurrency-limit $IA_PREFECT_WORKPOOL 1
      containers:
        - name: {{ .Values.app }}-worker
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: 
            - sh
            - -c
            - |
              prefect worker start --pool $IA_PREFECT_WORKPOOL
          volumeMounts:
            - name: {{ .Values.app }}-data
              mountPath: {{ .Values.mount.target }}
